version: "2"
services:
  weatherflow2mqtt:
    image: PetrDa/weatherflow2mqtt:latest
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - UNIT_SYSTEM=imperial
      - LANGUAGE=en
      - RAPID_WIND_INTERVAL=0
      - DEBUG=False
      - ELEVATION=0
      - LATITUDE=00.0000
      - LONGITUDE=000.0000
      - ZAMBRETTI_MIN_PRESSURE=
      - ZAMBRETTI_MAX_PRESSURE=
      - WF_HOST=0.0.0.0
      - WF_PORT=50222
      - MQTT_HOST=
      - MQTT_PORT=1883
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
      - MQTT_DEBUG=False
      - STATION_ID=
      - STATION_TOKEN=
      - FORECAST_INTERVAL=30
    volumes:
      - /YOUR_STORAGE_AREA/PATH:/data
    ports:
      - 0.0.0.0:50222:50222/udp
